name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepare Deployment Directory
      run: |
        mkdir -p build
        cp -r Honda/* build/
        cd build
        git init
        git remote add origin https://github.com/${{ github.repository }}.git
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force --set-upstream origin gh-pages
